from Views.formAbbonamento import FormAbbonamento
from Views.formCapienza import FormCapienza
from Views.formCliente import FormCliente
from Views.formLogin import FormLogin
from Views.formOrario import FormOrario
from Views.formPagamento import FormPagamento
from Views.formPersonale import FormPersonale
from Views.formRegistrazione import FormRegistrazione
from Views.homePageAmministratore import HomePageAmministratore
from Views.homePageCliente import HomePageCliente
from Views.mainWindow import MainWindow