from Models.utente import Utente
from Models.certificatoMedico import CertificatoMedico
from Models.cliente import Cliente
from Models.abbonamento import Abbonamento
from Models.amministratore import Amministratore
from Models.corso import Corso
from Models.credenziali import Credenziali
from Models.fasciaOraria import FasciaOraria
from Models.ingresso import Ingresso
from Models.pagamento import Pagamento
from Models.salaPesi import SalaPesi
from Models.palestra import Palestra
from Models.prenotazione import Prenotazione
from Models.prenotazioneCorso import PrenotazioneCorso
from Models.prenotazioneSalaPesi import PrenotazioneSalaPesi
from Models.statistica import Statistica