from Models.utente import Utente
from Models.cliente import Cliente
from Models.amministratore import Amministratore
from Models.credenziali import Credenziali
from Models.certificatoMedico import CertificatoMedico
from Models.salaPesi import SalaPesi
from Models.corso import Corso
from Models.palestra import Palestra
from Models.fasciaOraria import FasciaOraria
from Models.abbonamento import Abbonamento
from Models.accesso import Accesso
from Models.pagamento import Pagamento
from Models.statistica import Statistica
from Models.prenotazione import Prenotazione
from Models.prenotazioneCorso import PrenotazioneCorso
from Models.prenotazioneSalaPesi import PrenotazioneSalaPesi